"""Static gate: the parameter-learning layer stays retired.

The layer was removed after six months in which it never produced a measurable
gain, while its contextual adjustments compounded tick-over-tick into a
standing +5 c/kWh inflation of the grid-charge price gate. It was investigated
and partially repaired three times (#170, #913, and again in September) before
it was cut — so the risk this guards is a well-earned one: a future change
reintroducing a module or a data field, and the whole cycle starting over.

Prose in a docstring decays; a failing test does not. Same shape as
test_tick_handlers_delegate.py, which exists because a code path sat orphaned
for five months while its tests stayed green.

If you are deliberately bringing learning back, do not edit this file to make
it pass. Read simulations/replay/README.md first, then delete this test in the
same commit that lands the replacement, so the removal is explicit in history.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from custom_components.localshift.coordinator.data import CoordinatorData

PACKAGE = Path(__file__).resolve().parent.parent / "custom_components" / "localshift"

# Modules deleted with the layer. Each implemented a piece of the loop:
# parameter search, pattern mining, the contextual overlay, and the TOU
# baseline comparison respectively.
RETIRED_MODULES = (
    "engine/parameters.py",
    "engine/pattern_analyzer.py",
    "engine/pattern_types.py",
    "engine/optimization_controller.py",
    "engine/counterfactual.py",
    "learning/orchestrator.py",
    "sensors/learning.py",
)

# CoordinatorData fields that only ever carried learning output. adaptive_params
# is deliberately NOT here: it survives at its zero default because the
# optimizer reads it unconditionally and zero is the identity.
RETIRED_FIELDS = (
    "optimization_weights",
    "contextual_adjustments_active",
    "pattern_report_summary",
    "active_bias_corrections",
    "last_pattern_analysis",
    "weather_anomaly_weight",
)


@pytest.mark.parametrize("relative", RETIRED_MODULES)
def test_retired_module_is_absent(relative: str) -> None:
    assert not (PACKAGE / relative).exists(), (
        f"{relative} is back. See this file's docstring before making it pass."
    )


@pytest.mark.parametrize("field_name", RETIRED_FIELDS)
def test_retired_field_is_absent(field_name: str) -> None:
    assert not hasattr(CoordinatorData(), field_name), (
        f"CoordinatorData.{field_name} is back — that field only ever carried "
        "parameter-learning output."
    )


def test_adaptive_params_survive_at_the_zero_identity() -> None:
    """The optimizer still reads the offsets, so the field must exist and be zero.

    engine/optimizer_runner.py applies cheap_price_bias, the two SOC margins and
    export_threshold_adjustment unconditionally. Removing the field would break
    the optimizer; letting it default to anything but zero would silently
    reintroduce the behaviour the ten-day replay was run to remove.
    """
    params = CoordinatorData().adaptive_params
    assert params.values == {}
    for name in (
        "cheap_price_bias",
        "export_threshold_adjustment",
        "grid_charge_soc_headroom",
        "overnight_drain_safety_margin",
    ):
        assert params.get(name, 0.0) == 0.0
    assert params.get("solar_confidence_factor", 1.0) == 1.0
