"""Static gate: the parameter-learning layer stays retired.

The layer was removed after six months in which it never produced a measurable
gain, while its contextual adjustments compounded tick-over-tick into a
standing +5 c/kWh inflation of the grid-charge price gate. It was investigated
and partially repaired three times (#170, #913, and again in September) before
it was cut — so the risk this guards is a well-earned one: a future change
reintroducing a module or a data field, and the whole cycle starting over.

Prose in a docstring decays; a failing test does not. Same shape as
test_tick_handlers_delegate.py, which exists because a code path sat orphaned
for five months while its tests stayed green.

If you are deliberately bringing learning back, do not edit this file to make
it pass. Read simulations/replay/README.md first, then delete this test in the
same commit that lands the replacement, so the removal is explicit in history.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from custom_components.localshift.coordinator.data import CoordinatorData

PACKAGE = Path(__file__).resolve().parent.parent / "custom_components" / "localshift"

# Modules deleted with the layer. Each implemented a piece of the loop:
# parameter search, pattern mining, the contextual overlay, and the TOU
# baseline comparison respectively.
RETIRED_MODULES = (
    "engine/parameters.py",
    "engine/pattern_analyzer.py",
    "engine/pattern_types.py",
    "engine/optimization_controller.py",
    "engine/counterfactual.py",
    "learning/orchestrator.py",
    "sensors/learning.py",
    "forecast/corrections.py",
)

# CoordinatorData fields that only ever carried learning output.
# adaptive_params joined this list in #982: the layer that populated it was
# already retired, and by then nothing wrote to it any more, so every read
# was at the arithmetic identity (zero offset, 1.0 factor) and the plumbing
# itself came out too.
RETIRED_FIELDS = (
    "optimization_weights",
    "contextual_adjustments_active",
    "pattern_report_summary",
    "active_bias_corrections",
    "last_pattern_analysis",
    "weather_anomaly_weight",
    "adaptive_params",
)


@pytest.mark.parametrize("relative", RETIRED_MODULES)
def test_retired_module_is_absent(relative: str) -> None:
    assert not (PACKAGE / relative).exists(), (
        f"{relative} is back. See this file's docstring before making it pass."
    )


@pytest.mark.parametrize("field_name", RETIRED_FIELDS)
def test_retired_field_is_absent(field_name: str) -> None:
    assert not hasattr(CoordinatorData(), field_name), (
        f"CoordinatorData.{field_name} is back — that field only ever carried "
        "parameter-learning output."
    )
