"""Load-sized target SOC for a price-only block (docs/PRICE_BLOCK_TARGET.md; #1108).

A price-only block charges to what the evening needs, not to ``battery_target``:

    clamp(minimum_target_soc + needed_pct + headroom,
          minimum_target_soc, battery_target)

With ``switch.localshift_price_block_target`` ON and no block the target is
``minimum_target_soc``, so the terminal machinery has nothing to enforce. With
the switch OFF the target is what it was before this change:
``price_block_switch_off_target_golden.json`` was captured from commit 96f75af,
the parent of this change, by the driver's ``capture_targets()``, and is never
regenerated by the test run.
"""

from __future__ import annotations

import copy
import json
from typing import Any

import pytest

from custom_components.localshift.const import (
    CONF_BATTERY_TARGET,
    CONF_MINIMUM_TARGET_SOC,
    DEFAULT_BATTERY_TARGET,
)
from custom_components.localshift.coordinator.data import CoordinatorData
from custom_components.localshift.engine.optimizer_runner import (
    apply_price_block,
    price_block_target_soc,
)
from custom_components.localshift.engine.target_block import (
    TargetBlock,
    find_target_block,
)
from custom_components.localshift.engine.types import OptimizerConfig, SlotContext
from scripts.replay_no_dw import LIVE_OVERRIDES
from tests.helpers.price_block_driver import (
    CAPTURE_0907,
    TARGET_GOLDEN,
    Run,
    drive,
    is_live,
    load,
    scenario_paths,
)

LIVE_MINIMUM = float(LIVE_OVERRIDES["minimum_target_soc"])
LIVE_TARGET = float(LIVE_OVERRIDES["battery_target"])


def _block(needed_pct: float) -> TargetBlock:
    return TargetBlock(
        entry_idx=4,
        end_idx=8,
        needed_kwh=needed_pct / 100.0 * 13.5,
        needed_pct=needed_pct,
        reason="test",
    )


# ---------------------------------------------------------------------------
# The sizing rule
# ---------------------------------------------------------------------------


def test_block_target_is_minimum_plus_need() -> None:
    assert price_block_target_soc(
        _block(30.0), minimum_target_soc=20.0, battery_target=95.0
    ) == pytest.approx(50.0)


def test_existing_headroom_is_added_to_the_need() -> None:
    assert price_block_target_soc(
        _block(30.0), minimum_target_soc=20.0, battery_target=95.0, headroom_pct=3.5
    ) == pytest.approx(53.5)


def test_need_beyond_one_battery_is_pinned_at_battery_target() -> None:
    # The real 2026-09-07 block needs about 220% of the battery.
    assert (
        price_block_target_soc(
            _block(220.0), minimum_target_soc=5.0, battery_target=95.0
        )
        == 95.0
    )


def test_headroom_cannot_lift_the_target_past_battery_target() -> None:
    assert (
        price_block_target_soc(
            _block(74.0), minimum_target_soc=20.0, battery_target=95.0, headroom_pct=5.0
        )
        == 95.0
    )


def test_no_block_targets_the_minimum() -> None:
    assert (
        price_block_target_soc(None, minimum_target_soc=20.0, battery_target=95.0)
        == 20.0
    )


def test_no_block_ignores_headroom() -> None:
    assert (
        price_block_target_soc(
            None, minimum_target_soc=20.0, battery_target=95.0, headroom_pct=5.0
        )
        == 20.0
    )


def test_block_needing_nothing_targets_the_minimum() -> None:
    assert (
        price_block_target_soc(_block(0.0), minimum_target_soc=20.0, battery_target=95)
        == 20.0
    )


def test_negative_headroom_cannot_pull_the_target_below_the_minimum() -> None:
    assert (
        price_block_target_soc(
            _block(2.0), minimum_target_soc=20.0, battery_target=95.0, headroom_pct=-9.0
        )
        == 20.0
    )


@pytest.mark.parametrize("needed", [float("nan"), float("inf"), float("-inf")])
def test_unusable_need_never_escapes_the_bounds(needed: float) -> None:
    target = price_block_target_soc(
        _block(needed), minimum_target_soc=20.0, battery_target=95.0
    )
    assert 20.0 <= target <= 95.0


def test_minimum_above_battery_target_yields_battery_target() -> None:
    """A misconfiguration: the ceiling wins, the target never exceeds it."""
    for block in (None, _block(30.0)):
        assert (
            price_block_target_soc(block, minimum_target_soc=90.0, battery_target=60.0)
            == 60.0
        )


@pytest.mark.parametrize("needed", [0.0, 0.4, 12.0, 74.9, 75.0, 75.1, 220.0, 1e6])
@pytest.mark.parametrize("headroom", [0.0, 2.0, 10.0])
def test_target_always_inside_the_bounds(needed: float, headroom: float) -> None:
    target = price_block_target_soc(
        _block(needed),
        minimum_target_soc=20.0,
        battery_target=95.0,
        headroom_pct=headroom,
    )
    assert 20.0 <= target <= 95.0


# ---------------------------------------------------------------------------
# apply_price_block: flags and target together, on the planner's config
# ---------------------------------------------------------------------------


def _slot(index: int, price: float, load_kwh: float) -> SlotContext:
    return SlotContext(
        slot_index=index,
        timestamp_iso=f"2026-09-07T{9 + index // 2:02d}:{30 * (index % 2):02d}:00+10:00",
        slot_interval_minutes=30,
        buy_price=price,
        sell_price=0.0,
        solar_kwh=0.0,
        consumption_kwh=load_kwh,
        is_demand_window_slot=False,
        is_demand_window_entry=False,
    )


# Cheap morning, then a five-slot dear evening from index 4.
_PRICES = [0.07, 0.07, 0.07, 0.07, 0.19, 0.19, 0.19, 0.19, 0.19, 0.07]
_OPTIONS = {CONF_BATTERY_TARGET: 95, CONF_MINIMUM_TARGET_SOC: 20}


def _day(load_kwh: float, prices: list[float] | None = None) -> list[SlotContext]:
    return [_slot(i, p, load_kwh) for i, p in enumerate(prices or _PRICES)]


def _config(**kwargs: Any) -> OptimizerConfig:
    return OptimizerConfig(
        battery_capacity_kwh=13.5,
        discharge_efficiency=0.95,
        min_soc_pct=20.0,
        demand_window_target_soc_pct=95.0,
        **kwargs,
    )


def test_switch_off_leaves_the_target_alone() -> None:
    config = _config(price_block_target=False)
    slots = _day(1.0)

    block = apply_price_block(slots, config, _OPTIONS, CoordinatorData())

    assert block is None
    assert config.demand_window_target_soc_pct == 95.0
    assert not any(s.is_demand_window_slot for s in slots)


def test_switch_on_sizes_the_target_to_the_block() -> None:
    config = _config(price_block_target=True)
    slots = _day(0.5)

    block = apply_price_block(slots, config, _OPTIONS, CoordinatorData())

    assert block is not None
    # Five slots of 0.5 kWh through a 95% discharge, of a 13.5 kWh battery.
    needed_pct = 5 * 0.5 / 0.95 / 13.5 * 100.0
    assert block.needed_pct == pytest.approx(needed_pct)
    assert config.demand_window_target_soc_pct == pytest.approx(20.0 + needed_pct)
    assert slots[4].is_demand_window_entry


def test_switch_on_adds_the_adaptive_headroom() -> None:
    config = _config(price_block_target=True)
    data = CoordinatorData()
    data.adaptive_params = {
        "grid_charge_soc_headroom": 2.0,
        "overnight_drain_safety_margin": 1.5,
    }

    block = apply_price_block(_day(0.5), config, _OPTIONS, data)

    assert block is not None
    assert config.demand_window_target_soc_pct == pytest.approx(
        20.0 + block.needed_pct + 3.5
    )


def test_switch_on_inflated_load_is_capped_at_battery_target() -> None:
    config = _config(price_block_target=True)

    block = apply_price_block(_day(6.0), config, _OPTIONS, CoordinatorData())

    assert block is not None
    assert block.needed_pct > 100.0
    assert config.demand_window_target_soc_pct == 95.0


def test_switch_on_without_a_block_targets_the_minimum() -> None:
    config = _config(price_block_target=True)
    slots = _day(1.0, prices=[0.15] * 10)

    block = apply_price_block(slots, config, _OPTIONS, CoordinatorData())

    assert block is None
    assert config.demand_window_target_soc_pct == 20.0


def test_switch_on_missing_options_fall_back_to_the_defaults() -> None:
    config = _config(price_block_target=True)

    block = apply_price_block(_day(6.0), config, {}, CoordinatorData())

    assert block is not None
    assert config.demand_window_target_soc_pct == float(DEFAULT_BATTERY_TARGET)


def test_persist_false_still_sizes_the_target() -> None:
    """The shadow plan is sized to its own block without moving the live entry."""
    config = _config(price_block_target=True)
    data = CoordinatorData()

    block = apply_price_block(_day(0.5), config, _OPTIONS, data, persist=False)

    assert block is not None
    assert config.demand_window_target_soc_pct == pytest.approx(20.0 + block.needed_pct)
    assert data.target_block_entry_iso is None


# ---------------------------------------------------------------------------
# Through the engine
# ---------------------------------------------------------------------------

_TARGET_RECORD: dict[str, Any] = json.loads(TARGET_GOLDEN.read_text())


def test_target_golden_covers_every_golden_fixture() -> None:
    assert sorted(_TARGET_RECORD["targets"]) == scenario_paths()


@pytest.mark.parametrize("path", scenario_paths())
@pytest.mark.parametrize("switch", [False, None], ids=["off", "absent"])
def test_switch_off_target_equals_pre_change_value(
    path: str, switch: bool | None
) -> None:
    run = drive(load(path), price_block_target=switch, live=is_live(path))

    assert run.target_soc == _TARGET_RECORD["targets"][path]


def _with_load(scenario: dict[str, Any], load_kw: float) -> dict[str, Any]:
    """The same day with a different load forecast (it is driven by recent load)."""
    scaled = copy.deepcopy(scenario)
    scaled["input"]["load_power_kw"] = load_kw
    return scaled


def _flat(scenario: dict[str, Any], price: float = 0.15) -> dict[str, Any]:
    flat = copy.deepcopy(scenario)
    for row in flat["input"]["general_forecast"]:
        for key in ("per_kwh", "price", "advanced_price_predicted", "spot_per_kwh"):
            if key in row:
                row[key] = price
    flat["input"]["general_price"] = price
    return flat


def _redetect(run: Run) -> TargetBlock | None:
    """The block the planner's own slots carry, found again from scratch."""
    return find_target_block(
        run.slots,
        OptimizerConfig(battery_capacity_kwh=13.5, discharge_efficiency=0.95),
    )


@pytest.fixture(scope="module")
def on_0907() -> Run:
    return drive(load(CAPTURE_0907), price_block_target=True, live=True)


def test_0907_net_cost_at_or_below_the_clock_window(on_0907: Run) -> None:
    """Acceptance: at or below 6.06 (the ``dw`` arm is $6.054)."""
    assert on_0907.result["projected_net_cost"] <= 6.06


def test_0907_need_exceeds_the_battery_so_target_is_battery_target(
    on_0907: Run,
) -> None:
    """The capture is the inflated-load case: about 220% of the battery."""
    block = _redetect(on_0907)

    assert block is not None
    assert block.needed_pct > 100.0
    assert on_0907.target_soc == LIVE_TARGET


def test_mild_evening_target_is_load_sized() -> None:
    """A mild evening charges to what it needs, not to battery_target."""
    run = drive(_with_load(load(CAPTURE_0907), 0.6), price_block_target=True, live=True)
    block = _redetect(run)

    assert block is not None
    assert run.target_soc == pytest.approx(LIVE_MINIMUM + block.needed_pct)
    assert LIVE_MINIMUM < run.target_soc < LIVE_TARGET


@pytest.mark.parametrize("load_kw", [0.05, 0.6, 2.0, 3.587, 7.2, 20.0])
def test_target_stays_inside_the_bounds_for_any_load_forecast(load_kw: float) -> None:
    """Including the 2026-09-05 shape: a load forecast doubled by extrapolation."""
    run = drive(
        _with_load(load(CAPTURE_0907), load_kw), price_block_target=True, live=True
    )

    assert run.target_soc is not None
    assert LIVE_MINIMUM <= run.target_soc <= LIVE_TARGET


def test_flat_price_day_targets_the_minimum() -> None:
    run = drive(_flat(load(CAPTURE_0907)), price_block_target=True, live=True)

    assert run.flags == "." * len(run.slots)
    assert run.target_soc == LIVE_MINIMUM
    assert run.charge_times() == []
