"""Price block wired into the planner's slot flags (docs/PRICE_BLOCK_TARGET.md; #1107).

With ``switch.localshift_price_block_target`` ON the detected block replaces the
clock demand window as the thing that sets ``is_demand_window_slot`` and
``is_demand_window_entry``. Everything downstream (terminal penalty, hard floor,
water level, urgency window, import ban) reads those two flags and follows.

The non-negotiable property is the first test: with the switch OFF the flags the
planner sees and the plan it produces are identical to the code before this
change. ``price_block_switch_off_golden.json`` was captured from commit 83badbb,
the parent of the wiring commit, by the driver's ``capture_all()``, and is never
regenerated by the test run.

Scenarios are driven by ``tests/helpers/price_block_driver.py`` the way
``scripts/replay_no_dw.py`` ``run_arm`` drives them: ``forecast_horizon_hours``
seeded before the first pass, two passes, the second reported (#1053).
"""

from __future__ import annotations

import copy
import json
from datetime import datetime
from typing import Any

import pytest

from custom_components.localshift.coordinator.data import CoordinatorData
from custom_components.localshift.engine.slots import apply_price_block_flags
from custom_components.localshift.engine.types import OptimizerConfig, SlotContext
from tests.helpers.price_block_driver import (
    CAPTURE_0903,
    CAPTURE_0907,
    GOLDEN,
    REPO,
    Run,
    drive,
    is_live,
    load,
    scenario_paths,
    tracked_scenario_paths,
)


def _local(stamp: str) -> str:
    return datetime.fromisoformat(stamp).strftime("%H:%M")


def _outcome(run: Run) -> dict[str, Any]:
    return {k: v for k, v in run.result.items() if k != "states_explored"}


def _flat(scenario: dict[str, Any], price: float = 0.15) -> dict[str, Any]:
    """The same day with every buy price flattened: nothing is dearer than anything."""
    flat = copy.deepcopy(scenario)
    for row in flat["input"]["general_forecast"]:
        for key in ("per_kwh", "price", "advanced_price_predicted", "spot_per_kwh"):
            if key in row:
                row[key] = price
    flat["input"]["general_price"] = price
    return flat


# ---------------------------------------------------------------------------
# Switch OFF: identical to the code before this change
# ---------------------------------------------------------------------------

_GOLDEN_RECORD: dict[str, Any] = json.loads(GOLDEN.read_text())


def test_golden_fixtures_are_all_present() -> None:
    """Every fixture the golden names must exist, in a clean checkout too."""
    missing = [path for path in scenario_paths() if not (REPO / path).is_file()]
    assert not missing


def test_golden_covers_every_tracked_scenario_fixture() -> None:
    """A fixture committed later must be added to the golden, not silently skipped.

    Compared against what git tracks, not what is on disk: the replay days that
    ``.gitignore`` excludes exist on some machines only and are not in the golden.
    """
    tracked = tracked_scenario_paths()
    if tracked is None:
        pytest.skip("not a git checkout: cannot list tracked fixtures")
    assert scenario_paths() == tracked


@pytest.mark.parametrize("path", scenario_paths())
@pytest.mark.parametrize("switch", [False, None], ids=["off", "absent"])
def test_switch_off_is_identical_to_pre_change_code(
    path: str, switch: bool | None
) -> None:
    run = drive(load(path), price_block_target=switch, live=is_live(path))
    want = _GOLDEN_RECORD["scenarios"][path]
    got = run.snapshot()

    assert got["flags"] == want["flags"]
    assert got["actions"] == want["actions"]
    assert got["projected_net_cost"] == want["projected_net_cost"]
    assert got["digest"] == want["digest"]
    assert run.data.target_block_entry_idx is None
    assert run.data.target_block_entry_iso is None


# ---------------------------------------------------------------------------
# Switch ON: 2026-09-07, the day the clock window cannot fund
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def on_0907() -> Run:
    return drive(load(CAPTURE_0907), price_block_target=True, live=True)


def test_0907_block_replaces_the_clock_window_flags(on_0907: Run) -> None:
    slots = on_0907.slots
    flagged = [s for s in slots if s.is_demand_window_slot]
    entries = [s for s in slots if s.is_demand_window_entry]

    assert len(entries) == 1
    assert _local(entries[0].timestamp_iso) == "16:30"
    assert flagged[0] is entries[0]
    assert _local(flagged[-1].timestamp_iso) == "00:00"
    # Contiguous: the block, the whole block and nothing but the block.
    assert [s.slot_index for s in flagged] == list(
        range(flagged[0].slot_index, flagged[-1].slot_index + 1)
    )
    # The clock window's 15:00-16:00 slots are not in it.
    early = [s for s in slots if _local(s.timestamp_iso) in ("15:00", "15:30", "16:00")]
    assert early
    assert not any(s.is_demand_window_slot for s in early)


def test_0907_plan_grid_charges_before_block_entry(on_0907: Run) -> None:
    entry = next(s for s in on_0907.slots if s.is_demand_window_entry)
    entry_at = datetime.fromisoformat(entry.timestamp_iso)
    charges = on_0907.charge_times()

    assert charges, "the block funded no pre-charge"
    assert any(t < entry_at for t in charges)


def test_0907_plan_schedules_no_grid_charge_after_2100(on_0907: Run) -> None:
    first = datetime.fromisoformat(on_0907.decisions[0]["timestamp_iso"])
    nine_pm = first.replace(hour=21, minute=0, second=0, microsecond=0)

    late = [t for t in on_0907.charge_times() if t >= nine_pm]
    assert late == []


def test_0907_entry_is_persisted_for_hysteresis(on_0907: Run) -> None:
    entry = next(s for s in on_0907.slots if s.is_demand_window_entry)

    assert on_0907.data.target_block_entry_idx == entry.slot_index
    assert on_0907.data.target_block_entry_iso == entry.timestamp_iso


def test_0907_held_entry_survives_the_engine(on_0907: Run) -> None:
    """A previous plan one slot later than the fresh detection holds the entry."""
    entry = next(s for s in on_0907.slots if s.is_demand_window_entry)
    later = on_0907.slots[entry.slot_index + 1]

    held = drive(
        load(CAPTURE_0907),
        price_block_target=True,
        live=True,
        previous_entry_iso=later.timestamp_iso,
    )

    held_entry = next(s for s in held.slots if s.is_demand_window_entry)
    assert held_entry.timestamp_iso == later.timestamp_iso
    assert held.data.target_block_entry_idx == later.slot_index


# ---------------------------------------------------------------------------
# Switch ON: a day solar fills the battery, and a day with nothing to prepare for
# ---------------------------------------------------------------------------


def test_solar_fills_battery_day_plans_the_same_on_and_off() -> None:
    scenario = load(CAPTURE_0903)
    off = drive(scenario, price_block_target=False, live=True)
    on = drive(scenario, price_block_target=True, live=True)

    # The block is there and is not the clock window, so this is not a no-op.
    assert "E" in on.flags
    assert on.flags != off.flags

    assert [d["action"] for d in on.decisions] == [d["action"] for d in off.decisions]
    assert on.decisions == off.decisions
    # states_explored counts search effort, which follows the flags; every
    # outcome of the plan is the same.
    assert _outcome(on) == _outcome(off)


def test_flat_price_day_has_no_block_and_no_grid_charge() -> None:
    run = drive(_flat(load(CAPTURE_0907)), price_block_target=True, live=True)

    assert run.slots
    assert {s.buy_price for s in run.slots} == {0.15}
    assert run.flags == "." * len(run.slots)
    assert run.charge_times() == []
    assert run.data.target_block_entry_idx is None
    assert run.data.target_block_entry_iso is None


# ---------------------------------------------------------------------------
# apply_price_block_flags in isolation
# ---------------------------------------------------------------------------


def _slot(index: int, price: float, *, clock_dw: bool = False) -> SlotContext:
    return SlotContext(
        slot_index=index,
        timestamp_iso=f"2026-09-07T{9 + index // 2:02d}:{30 * (index % 2):02d}:00+10:00",
        slot_interval_minutes=30,
        buy_price=price,
        sell_price=0.0,
        solar_kwh=0.0,
        consumption_kwh=1.0,
        is_demand_window_slot=clock_dw,
        is_demand_window_entry=False,
    )


def _day(prices: list[float], clock_dw: tuple[int, ...] = ()) -> list[SlotContext]:
    slots = [_slot(i, p, clock_dw=i in clock_dw) for i, p in enumerate(prices)]
    if clock_dw:
        slots[clock_dw[0]].is_demand_window_entry = True
    return slots


def _flags(slots: list[SlotContext]) -> str:
    return "".join(
        "E" if s.is_demand_window_entry else "D" if s.is_demand_window_slot else "."
        for s in slots
    )


_ON = OptimizerConfig(price_block_target=True)
# Cheap morning, then a five-slot dear evening from index 4.
_PRICES = [0.07, 0.07, 0.07, 0.07, 0.19, 0.19, 0.19, 0.19, 0.19, 0.07]


def test_switch_off_leaves_slots_and_state_alone() -> None:
    slots = _day(_PRICES, clock_dw=(2, 3))
    data = CoordinatorData()
    data.target_block_entry_idx = 7
    data.target_block_entry_iso = "stale"

    block = apply_price_block_flags(slots, OptimizerConfig(), data)

    assert block is None
    assert _flags(slots) == "..ED......"
    assert data.target_block_entry_idx is None
    assert data.target_block_entry_iso is None


def test_block_overwrites_the_clock_window() -> None:
    slots = _day(_PRICES, clock_dw=(1, 2, 3, 4, 5))
    data = CoordinatorData()

    block = apply_price_block_flags(slots, _ON, data)

    assert block is not None
    assert (block.entry_idx, block.end_idx) == (4, 8)
    assert _flags(slots) == "....EDDDD."
    assert data.target_block_entry_idx == 4
    assert data.target_block_entry_iso == slots[4].timestamp_iso


def test_no_block_clears_every_flag_and_the_stored_entry() -> None:
    slots = _day([0.15] * 10, clock_dw=(4, 5, 6))
    data = CoordinatorData()
    data.target_block_entry_idx = 4
    data.target_block_entry_iso = slots[4].timestamp_iso

    block = apply_price_block_flags(slots, _ON, data)

    assert block is None
    assert _flags(slots) == "." * 10
    assert data.target_block_entry_idx is None
    assert data.target_block_entry_iso is None


def test_previous_entry_is_matched_by_time_not_by_index() -> None:
    """The horizon slides between plans, so a stored index means a later slot.

    The previous plan entered at 11:30. Half an hour on, the same 11:30 slot is
    one index earlier. Matching by index would see 5 against a fresh 4 and hold
    the entry one slot late on every re-plan; matching by time sees no change.
    """
    earlier = _day([0.07, *_PRICES])
    data = CoordinatorData()
    apply_price_block_flags(earlier, _ON, data)
    assert data.target_block_entry_idx == 5
    entered_at = data.target_block_entry_iso

    later = _day(_PRICES)
    for slot in later:
        slot.timestamp_iso = earlier[slot.slot_index + 1].timestamp_iso
    block = apply_price_block_flags(later, _ON, data)

    assert block is not None
    assert block.entry_idx == 4
    assert later[4].timestamp_iso == entered_at
    assert "held" not in block.reason


def test_previous_entry_one_slot_away_is_held() -> None:
    slots = _day(_PRICES)
    data = CoordinatorData()
    data.target_block_entry_iso = slots[5].timestamp_iso

    block = apply_price_block_flags(slots, _ON, data)

    assert block is not None
    assert block.entry_idx == 5
    assert _flags(slots) == ".....EDDD."
    assert data.target_block_entry_idx == 5


def test_previous_entry_two_slots_away_is_not_held() -> None:
    slots = _day(_PRICES)
    data = CoordinatorData()
    data.target_block_entry_iso = slots[6].timestamp_iso

    block = apply_price_block_flags(slots, _ON, data)

    assert block is not None
    assert block.entry_idx == 4


@pytest.mark.parametrize("stale", ["2026-09-06T16:30:00+10:00", "not a timestamp"])
def test_previous_entry_outside_the_horizon_is_ignored(stale: str) -> None:
    slots = _day(_PRICES)
    data = CoordinatorData()
    data.target_block_entry_iso = stale

    block = apply_price_block_flags(slots, _ON, data)

    assert block is not None
    assert block.entry_idx == 4


def test_previous_entry_inside_a_split_slot_maps_to_its_first_piece() -> None:
    """A 30-minute slot becomes 5-minute slots as it nears; the boundary is the same."""
    slots = _day(_PRICES)
    stamp = slots[5].timestamp_iso
    data = CoordinatorData()
    # Five minutes into slot 5: no slot starts there, so it is the slot covering it.
    data.target_block_entry_iso = stamp.replace(":30:00", ":35:00").replace(
        ":00:00+", ":05:00+"
    )

    block = apply_price_block_flags(slots, _ON, data)

    assert block is not None
    assert block.entry_idx == 5


def test_persist_false_reads_the_previous_entry_but_does_not_write() -> None:
    """The shadow comparison plans on other prices and must not move the entry."""
    slots = _day(_PRICES)
    data = CoordinatorData()
    data.target_block_entry_idx = 9
    data.target_block_entry_iso = slots[5].timestamp_iso

    block = apply_price_block_flags(slots, _ON, data, persist=False)

    assert block is not None
    assert block.entry_idx == 5
    assert data.target_block_entry_idx == 9
    assert data.target_block_entry_iso == slots[5].timestamp_iso


def test_empty_horizon_is_harmless() -> None:
    data = CoordinatorData()
    assert apply_price_block_flags([], _ON, data) is None
    assert data.target_block_entry_idx is None
